"""Public demo UI for the claims triage agent.

Upload a PDF medical report and view the structured decision output generated by
the backend agent in ``src.agent``.
"""

import json
import os
import tempfile

import streamlit as st
from dotenv import load_dotenv
from openai import OpenAI

from src.agent import DEFAULT_MODEL, run_claims_agent
from src.ingest import pdf_to_text


def _build_client() -> tuple[OpenAI, str]:
    """Initialize OpenAI client and model from env vars or Streamlit secrets."""
    load_dotenv()

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        api_key = st.secrets.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not found. Set it in .env or Streamlit secrets.")

    model = os.getenv("OPENAI_MODEL")
    if not model:
        model = st.secrets.get("OPENAI_MODEL", DEFAULT_MODEL)

    return OpenAI(api_key=api_key), model


def _extract_text_from_uploaded_pdf(uploaded_file) -> str:
    """Persist uploaded bytes to a temp PDF and extract text."""
    with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp_file:
        tmp_file.write(uploaded_file.getvalue())
        tmp_path = tmp_file.name

    try:
        return pdf_to_text(tmp_path)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


def main() -> None:
    """Render the demo UI and orchestrate upload -> decision flow."""
    st.set_page_config(page_title="Claims Triage Agent Demo", page_icon=":page_facing_up:")
    st.title("Claims Triage Agent Demo")
    st.caption("Upload a sample medical report PDF to generate an underwriting triage recommendation.")

    st.warning(
        "Demo use only. Upload synthetic/sample documents only. Do not upload real patient PHI."
    )

    uploaded = st.file_uploader("Upload medical report (PDF)", type=["pdf"])

    if not uploaded:
        st.info("Upload a PDF to run the agent.")
        return

    if st.button("Run Agent", type="primary"):
        with st.spinner("Analyzing report and generating decision..."):
            try:
                client, model = _build_client()
                document_text = _extract_text_from_uploaded_pdf(uploaded)
                if not document_text.strip():
                    st.error("No text extracted from PDF. It may be scanned/image-only.")
                    return

                session = run_claims_agent(
                    document_text=document_text,
                    client=client,
                    model=model,
                    verbose=False,
                )
            except Exception as exc:
                st.error(f"Failed to process document: {exc}")
                return

        decision = session.get("final_decision") or {}

        st.subheader("Agent Decision")
        c1, c2 = st.columns(2)
        c1.metric("Decision", decision.get("decision", "N/A"))
        c2.metric("Confidence", decision.get("confidence", "N/A"))

        st.markdown("**Rationale**")
        st.write(decision.get("rationale", "No rationale returned."))

        action_items = decision.get("action_items") or []
        if action_items:
            st.markdown("**Action Items**")
            for item in action_items:
                st.write(f"- {item}")

        docs_requested = decision.get("documents_requested") or []
        if docs_requested:
            st.markdown("**Documents Requested**")
            for item in docs_requested:
                st.write(f"- {item}")

        notes = decision.get("underwriter_notes")
        if notes:
            st.markdown("**Underwriter Notes**")
            st.write(notes)

        st.markdown("**Agent Summary**")
        st.write(session.get("agent_summary") or "No summary returned.")

        with st.expander("Full Session JSON"):
            st.code(json.dumps(session, indent=2), language="json")


if __name__ == "__main__":
    main()
